### ISSUE TITLE
Need an API to fetch all the applied leaves for a single Employee

### ISSUE THREAD

**Issue by jiteshdhamija** [jiteshdhamija/LeafMS-BackEnd#10]
API that is able to fetch all the leave data of a single employee

**Comment by hrishivarun** [comment]
`/leaves` GET API is capable of doing it, but only the employee him/herself can view his/her applied leaves on this API.
`/applications` GET API will let the **Approver** see all the leaves applied by those under him.


For `admin` to be able to see all the leaves is still to be implemented.
In fact,  the whole setup for admin user is still to be implemented.

**Comment by hrishivarun** [comment]
`/applications` GET API will let the **Approver** see all the leaves applied by those under him.


For `admin` to be able to see all the leaves is still to be implemented.
In fact,  the whole setup for admin user is still to be implemented.
